# -*- coding: utf-8 -*-
"""AI_Agent_Tutorial_StudyBuddy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-alsQguuw26G7t9JmOVQb2VdDU_rPVi3
"""

!pip -q install -U langchain langchain-google-genai xhtml2pdf

from google.colab import userdata
userdata.get('GOOGLE_API_KEY')

from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(
    model = "gemini-3.6-flash",
    temperature = 0.7,
    max_output_tokens = 4096,
    api_key = userdata.get('GOOGLE_API_KEY')
)

!pip install --upgrade langchain-google-genai google-genai

result = llm.invoke("What is AI")

result.content[0]["text"]

def ask_llm(query: str):
        response = llm.invoke(query)
        return response.text
print(ask_llm("In one short sentence, what can an AI agent do that a plain chatbot can't?"))

from langchain.tools import tool
@tool
def add(a:int,b:int):
  "This tool is used to add two number , use this tool for that"
  return a+b

from langchain.agents import create_agent
calculator_agent = create_agent(
    model = llm,
    tools = [add]
)

def run_agent( agent , query: str):
  "Run an agent on one query, print which tools it used, then print its final answer."
  result = agent.invoke({"messages":[{"role": "user", "content":query}]})
  print("tools called")
  for msg in result["messages"]:
    for call in getattr(msg,"tool_calls",None)or []:
      print(f"->{call["name"]}({call["args"]})")
  final_message = result["messages"][-1]
  print("final answer")
  return result

@tool
def save_todo(filename: str,text: str):
  "Save plain text or a to-do list to a markdown/text file on disk."
  with open(filename,"w") as f:
    f.write(text)
  return f"Saved {filename}"
@tool
def read_todo(filename: str):
  "Read a to-do list from a markdown/text file on disk."
  with open(filename,"r") as f:
    return f.read()

@tool
def save_html(filename: str,html_content: str):
  """ Tool: Generate & Save HTML """
  if not filename.endswith(".html"):
    filename = filename + ".html"
  with open(filename,"w",encoding="utf-8") as f:
    f.write(html_content)
  return f"HTML saved to {filename}"

from xhtml2pdf import pisa

# `xhtml2pdf` turns a saved HTML file into a downloadable PDF — handy for notes or itineraries the student wants offline.
@tool
def convert_pdf(html_filename: str, pdf_filename: str = "") -> str:
    """Convert a previously saved HTML file into a PDF file."""
    if not pdf_filename:
        pdf_filename = html_filename.rsplit('.', 1)[0] + ".pdf"

    with open(html_filename, "r", encoding="utf-8") as f:
        html_content = f.read()

    with open(pdf_filename, "wb") as pdf_file:
        pisa.CreatePDF(html_content, dest=pdf_file)

    return f"PDF saved to {pdf_filename}"

from IPython.display import display, HTML as IPHTML, Javascript
import base64
@tool
def render_html(filename: str, mode: str = "notebook")->str:
  "Render a saved HTML file. Use mode=\"notebook\" to display it inline,\n"
  "or mode=\"browser\" to open it in a new browser tab."
  with open(filename, "r", encoding="utf-8") as f:
    html_content = f.read()
  if mode == "browser":
    b64 = base64.b64encode(html_content.encode("utf-8")).decode('ascii')
    js = f"""
    const bytes = Uint8Array.from(atob("{b64}"), c => c.charCodeAt(0));
    const blob = new Blob([bytes], {{type: "text/html"}});
    const url = URL.createObjectURL(blob);
    window.open(url,'_blank');t
    """
    display(Javascript(js))
    return f"Opened {filename} in new browser tab"
  display(IPHTML(html_content))
  return f"Rendered {filename} inline in the notebook."

### Quick Pipeline Check
"Test that save → render → PDF all work before wiring them into the agent."

test_html = """
<html><body style="font-family:sans-serif;background:#fff7e6;padding:20px;">
<h1 style="color:#d97706;">Pipeline test</h1>
<p>If you can see this styled box, save_html + render_html both work!</p>
</body></html>
"""

save_html.invoke({"filename": "test.html", "html_content": test_html})
convert_pdf.invoke({"html_filename": "test.html"})
render_html.invoke({"filename": "test.html", "mode": "notebook"})

### Bonus Tools: Budget, Checklist & Memory
"These make the final agent genuinely useful: math for the travel budget, a simple checklist formatter, and a tiny memory file so the agent remembers things about the student between turns."

@tool
def calculate_budget(total_budget: float,items:dict)->str:
  """Given a total budget and a dictionary of item names to their cost,
    (e.g. {\"hotel\": 6000, \"food\": 3000}), return the total spent, the amount,
    remaining, and whether the plan is within budget."""
  total_spent = sum(items.values())
  remaining = total_budget - total_spent
  breakdown = "\n".join(f"-{name}: Rs.{cost}" for name, cost in items.items())
  status = "within budget" if remaining >= 0 else "Over Budget"
  within_budget = remaining >= 0
  return (
            f"Total spent: Rs.{total_spent}\\n {breakdown}\\n",
            f"Total spent: Rs.{total_spent}\\n Remaining: Rs.{remaining} ({status})\n",
        )
@tool
def generate_checklist(topic: str, items: list)->str:
  """Turn a topic and a list of item strings into a markdown checklist"""
  lines = [f"## {topic} checklist",""]
  lines +=[f"- []{item}" for item in items]
  return "\n".join(lines)

MEMORY_FILE= "Memory.md"
@tool
def save_memory(fact: str)->str:
  """Append one important fact about the student (their preferences,goals,\n,
  or context) to Memory.md so future conversations can use it."""
  with open(MEMORY_FILE,"a") as f:
    f.write("-\n"+fact)
  return f"Saved {fact} to {MEMORY_FILE}"
@tool
def load_memory() ->str:
  """Read and return everything currently saved about the student in Memory.md"""
  if not os.path.exists(MEMORY_FILE):
    return "No memory saved yet."
  with open(MEMORY_FILE,"r") as f:
    content= f.read().strip()
  return content if content else "No memory saved yet."

"""5. Assembling the Full Agent: StudyBuddy
    "Now we combine every tool above into one toolbox, and give the agent a **system prompt** — instructions on its personality and *when* to use each tool."
"""

tools = [
    save_todo,
    read_todo,
    save_html,
    convert_pdf,
    render_html,
    calculate_budget,
    generate_checklist,
    save_memory,
    load_memory,
]
print(f"Toolbox assembled with {len(tools)} tools:")
for t in tools:
  print(f"- {t.name}:{t.description}")

SYSTEM_PROMPT = """ You are StudyBuddy, a warm and encouraging AI companion for students.
You can:,
    - Write clear, visually appealing study notes as HTML (use headings, inline
      CSS colors, and a couple of relevant emojis), save them with save_html,
      and turn them into PDFs with convert_pdf.
    - Plan fun, budget-friendly student travel itineraries: check the numbers
      with calculate_budget, then build a colorful HTML itinerary and turn it
      into a PDF.
    - Build short, fun HTML quiz/revision games (multiple choice questions with
      a \"Check Answers\" button using simple JavaScript) and show them with
      render_html.
    - Remember important facts about the student using save_memory, and check
      load_memory whenever it would help personalize your answer.

    Always:
    1. Think about which tool(s) the request needs before acting.
    2. Keep HTML styling simple (inline CSS, no flexbox/grid) since it may be
       converted to PDF.
    3. After using tools, reply with a short, friendly summary of what you did
       and which file(s) you created.
    4. Keep your tone warm and encouraging, like a helpful older sibling - never
       robotic or overly formal."""
studybuddy_agent = create_agent(
    model = llm,
    tools = tools,
    system_prompt = SYSTEM_PROMPT
)

"""6. Demo: Generating an Educational Quiz Game,
    
    "Ask the agent for a self-contained HTML quiz game. Watch the tool trace — it should call `save_html` (and often `render_html`) on its own, with no extra instructions from us.
"""

run_agent(
    studybuddy_agent,
    """Create a fun 5-question multiple-choice quiz game about the water
    cycle for a school student, with a 'Check Answers' button. Save it as
    water_cycle_quiz.html and show it to me."""
)

run_agent(
    studybuddy_agent,
    """I'm a student planning a 3-day trip to Goa with a total budget of
    Rs.15000. Create a colorful HTML day-by-day itinerary that also shows
    the budget breakdown, save it as goa_trip.html, convert it to PDF
    and remember that I'm planning this trip."""
)

def run_agent_stream(agent, query: str):
  """Same as run_agent, but prints the reply live, token by token."""
  announced_tools = set()

  for chunk,metadata in agent.stream(
      {"messages": [{"role": "user", "content": query}]},
      stream_mode= "messages"
  ):
      for tc in getattr(chunk,"tool_call_chunks",None) or []:
        name = tc.get("name")
        if name and name not in announced_tools:
          announced_tools.add(name)
          print(f"\n[calling{name}...]\n")
      if metadata.get("langgraph_node") != "model":
        continue
      if chunk.text:
        print(chunk.text,end="",flush=True)
  print()

run_agent_stream(
    studybuddy_agent,
    "Give me a checklist of 4 things a student should pack for a college trip."
)

"""## Recap
    
    You went from a single plain-text LLM call to a multi-tool agent that can plan, write, save, convert, and remember things.

    Ideas to extend this:
    - Add a tool that fetches real weather or prices from an API.
    - Give the agent long-term memory using a vector database instead of a flat file.- Add more mini-games (flashcards, crosswords) reusing the same `save_html` + `render_html` pattern.
"""